"""Labeled, reversible failure injection for the Memory Health demo.

Every row this script writes carries an agent_id prefixed 'demo-', so the whole
demo is removable with one predicate.  Nothing here simulates a failure: the
records, embeddings, retrievals and similarity scores are all real, produced by
the same code paths production uses.  The only thing that is staged is *which*
data goes in.

    python demo_harness.py seed
    python demo_harness.py inject degradation
    python demo_harness.py heal degradation
    python demo_harness.py timeline --hours 6
    python demo_harness.py reset

Add --pause to stop before each phase so a narrator can catch up.
"""

from __future__ import annotations

import argparse
import random
import sys
import textwrap
from datetime import datetime, timedelta, timezone
from typing import Any, Iterable

import psycopg

import checks
from memory import (
    DEFAULT_MIN_SIMILARITY,
    EMBED_DIM,
    _to_vector,
    connect,
    embed,
    get_floor,
    recall,
    set_floor,
    write_memory,
)

# ---------------------------------------------------------------------------
# Safety: everything this script touches lives behind this prefix.
# ---------------------------------------------------------------------------
DEMO_PREFIX = "demo-"
DEMO_LIKE = "demo-%"

AGENT_MAIN = "demo-agent-01"
AGENT_STALE = "demo-stale-writer"
AGENT_EVICT = "demo-evict-heavy"
AGENT_DRIFT = "demo-drift-writer"
SESSION = "demo-session"

TABLES = ("memory_records", "memory_retrievals", "memory_health_events", "agent_config")

# ---------------------------------------------------------------------------
# Demo corpus -- a plausible infrastructure assistant's memory.
# ---------------------------------------------------------------------------
CORPUS: list[tuple[str, str]] = [
    ("fact", "The production database is CockroachDB v26.2 running on AWS in us-east-1."),
    ("fact", "Embeddings are generated by Bedrock Titan Text v2 at 1024 dimensions, unit-normalised."),
    ("fact", "The memory health checks run as a Lambda on a five minute EventBridge schedule."),
    ("fact", "Retrieval applies a cosine similarity floor of 0.35 before returning results."),
    ("fact", "The staging cluster shares a VPC with production but uses a separate database."),
    ("fact", "Nightly backups run at 02:00 UTC and are retained for thirty days."),
    ("decision", "We chose row-level TTL over a cleanup job because CockroachDB prunes expired rows itself."),
    ("decision", "We rejected pgvector on RDS because the team wanted multi-region writes later."),
    ("decision", "Health events are kept for seven days; longer trends belong in a metrics store."),
    ("incident", "On 12 June the embedding pipeline wrote null vectors for four hours after a Bedrock timeout."),
    ("incident", "A schema migration in May locked the retrievals table and blocked writes for nine minutes."),
    ("conversation", "The user prefers terse status updates and dislikes long preambles."),
    ("conversation", "The user asked to be paged only for critical severity, not warnings."),
    ("conversation", "The user works in Pacific time and prefers deploys before 15:00 local."),
]

# Every query below was measured against this corpus and clears the 0.35 floor
# with margin (lowest 0.49).  Phrasings that merely *look* on-topic are not
# good enough: "what timezone does the user work in?" retrieves exactly the
# right record and still scores 0.358, which would poison a healthy baseline.
ON_TOPIC_QUERIES = [
    "why were health events kept for only seven days?",          # 0.756
    "what does the staging cluster share with production?",      # 0.704
    "which database are we running in production?",              # 0.698
    "what is the similarity floor for retrieval?",               # 0.686
    "what time of day does the user prefer deploys?",            # 0.659
    "when do backups run?",                                      # 0.583
    "how do the memory health checks run?",                      # 0.562
    "why did we pick TTL instead of a cleanup job?",             # 0.575
    "which severity should page the user?",                      # 0.532
    "what does the schema migration incident in May tell us?",   # 0.529
    "how are embeddings generated?",                             # 0.505
    "why did we not use pgvector?",                              # 0.491
]

# Semantically distant from every record above -- the vector search still
# returns its k nearest rows, and every one of them falls below the floor.
OFF_TOPIC_QUERIES = [
    "sourdough starter hydration ratios for a cold kitchen",
    "pruning schedule for autumn raspberry canes",
    "best telescope eyepiece for observing Saturn's rings",
    "offside rule interpretation in five-a-side football",
    "how to re-tension a bicycle wheel with loose spokes",
    "watercolour techniques for painting fog over water",
    "tuning a mandolin to open G",
    "identifying wild mushrooms by spore print colour",
    "knitting a raglan sleeve top-down",
    "restoring a cast iron pan after rust",
]

# Measured to land in the near-miss band (0.20-0.35 against a 0.35 floor).
# Every one of these retrieves the semantically CORRECT record and is rejected
# anyway -- that is the whole point: these are false negatives, not misses.
NEAR_MISS_QUERIES = [
    "what did we decide about vector storage?",          # 0.323 -> pgvector decision
    "how often do the health checks run?",               # 0.323 -> health check cadence
    "remind me about the deploy window",                 # 0.315 -> deploy preference
    "tell me about the outage we had",                   # 0.282 -> May migration incident
    "what is the situation with paging?",                # 0.276 -> paging preference
    "how long is data kept around?",                     # 0.267 -> 7-day health retention
    "were there any problems with writes recently?",     # 0.251 -> migration blocked writes
    "anything about how often things are archived?",     # 0.228 -> nightly backups
    "what happened during the June incident?",           # 0.226 -> June null-vector incident
]

STALE_FACTS = [
    "The on-call rotation lead is Dana for this quarter.",
    "The API gateway rate limit is 1000 requests per minute.",
    "The staging cluster has three nodes.",
    "Feature flag 'vector-rerank' is disabled in production.",
    "The billing plan is CockroachDB Basic with a $200 monthly cap.",
    "The team standup is at 09:30 Pacific.",
]

EVICTION_FACTS = [
    "Temporary scratch note from the current planning session.",
    "Cached summary of the latest deploy diff.",
    "Working set for the in-progress migration review.",
    "Draft answer awaiting user confirmation.",
    "Short-lived context for the current debugging thread.",
    "Interim tally of failed health checks this hour.",
]

PAUSE = False


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------
def phase(title: str, detail: str = "") -> None:
    print()
    print("─" * 74)
    print(f"  {title}")
    if detail:
        for line in textwrap.wrap(detail, 70):
            print(f"  {line}")
    print("─" * 74)
    if PAUSE:
        try:
            input("  [enter to run this phase, ctrl-c to stop] ")
        except (EOFError, KeyboardInterrupt):
            print("\n  stopped.")
            sys.exit(0)


def step(message: str) -> None:
    print(f"    {message}")


# ---------------------------------------------------------------------------
# Guards
# ---------------------------------------------------------------------------
def require_demo(agent_id: str) -> str:
    """No row leaves this module without a demo- prefix on its agent_id."""
    if not agent_id.startswith(DEMO_PREFIX):
        raise ValueError(
            f"refusing to touch agent_id {agent_id!r}: "
            f"demo_harness only writes agent ids prefixed {DEMO_PREFIX!r}"
        )
    return agent_id


def protected_counts(conn: psycopg.Connection) -> dict[str, int]:
    """Row counts for everything that is NOT demo data.

    coalesce() matters: health events can carry a NULL agent_id, and those are
    real check results that must be counted as protected.
    """
    counts = {}
    with conn.cursor() as cur:
        for table in TABLES:
            cur.execute(
                f"SELECT count(*) AS n FROM {table} "
                f"WHERE coalesce(agent_id, '') NOT LIKE %s",
                (DEMO_LIKE,),
            )
            counts[table] = cur.fetchone()["n"]
    return counts


def assert_untouched(before: dict[str, int], after: dict[str, int]) -> None:
    for table, n in before.items():
        if after[table] != n:
            raise RuntimeError(
                f"SAFETY VIOLATION: {table} non-demo rows changed "
                f"{n} -> {after[table]}. Aborting."
            )


def demo_counts(conn: psycopg.Connection) -> dict[str, int]:
    counts = {}
    with conn.cursor() as cur:
        for table in TABLES:
            cur.execute(
                f"SELECT count(*) AS n FROM {table} WHERE agent_id LIKE %s",
                (DEMO_LIKE,),
            )
            counts[table] = cur.fetchone()["n"]
    return counts


# ---------------------------------------------------------------------------
# Modes
# ---------------------------------------------------------------------------
def do_seed(conn: psycopg.Connection, recalls: int = 8) -> None:
    phase(
        "SEED — realistic corpus + healthy retrieval baseline",
        f"Writes {len(CORPUS)} memory records for {AGENT_MAIN} with real Titan "
        f"embeddings, then runs {recalls} real recall() calls with on-topic "
        "queries. Every retrieval clears the similarity floor, so the baseline "
        "is genuinely healthy rather than an empty window.",
    )

    require_demo(AGENT_MAIN)
    with conn.cursor() as cur:
        cur.execute(
            "SELECT count(*) AS n FROM memory_records WHERE agent_id = %s", (AGENT_MAIN,)
        )
        existing = cur.fetchone()["n"]
    if existing:
        step(f"{AGENT_MAIN} already has {existing} records — skipping corpus write")
    else:
        for kind, content in CORPUS:
            write_memory(AGENT_MAIN, SESSION, kind, content, conn=conn)
        step(f"wrote {len(CORPUS)} records for {AGENT_MAIN}")

    cleared = 0
    for query in ON_TOPIC_QUERIES[:recalls]:
        hits = recall(AGENT_MAIN, query, session_id=SESSION, conn=conn)
        cleared += 1 if hits else 0
        top = f"{hits[0]['similarity']:.4f}" if hits else "floored"
        step(f"recall {top:>8}  {len(hits)} hit(s)  {query[:52]}")
    step(f"{cleared}/{recalls} retrievals cleared the {DEFAULT_MIN_SIMILARITY} floor")


def inject_stale(conn: psycopg.Connection, count: int = 6, days: float = 3.0) -> None:
    phase(
        "INJECT: staleness",
        f"Writes {count} records whose effective_as_of is backdated {days} days "
        "while written_at stays now(). They look freshly written to anything "
        "reading written_at, but the facts they carry aged out long ago.",
    )
    require_demo(AGENT_STALE)
    backdated = datetime.now(timezone.utc) - timedelta(days=days)
    for content in STALE_FACTS[:count]:
        write_memory(
            AGENT_STALE, SESSION, "fact", content,
            effective_as_of=backdated,
            metadata={"demo": "stale-injection"},
            conn=conn,
        )
    step(f"wrote {count} records, effective_as_of = {backdated:%Y-%m-%d %H:%M} UTC")
    step("written_at = now(), so written_at-based freshness sees nothing wrong")


def inject_eviction(conn: psycopg.Connection, count: int = 8) -> None:
    phase(
        "INJECT: eviction pressure",
        f"Writes {count} records whose expires_at lands inside the 60 minute "
        "pressure window. The corpus still answers every query right now, and "
        "is about to lose a large share of itself.",
    )
    require_demo(AGENT_EVICT)
    now = datetime.now(timezone.utc)
    for i, content in enumerate(EVICTION_FACTS * 2):
        if i >= count:
            break
        expires = now + timedelta(minutes=random.uniform(4, 55))
        write_memory(
            AGENT_EVICT, SESSION, "snapshot", content,
            expires_at=expires,
            metadata={"demo": "eviction-injection"},
            conn=conn,
        )
    step(f"wrote {count} records expiring within the next 55 minutes")


def inject_degradation(conn: psycopg.Connection, count: int = 10) -> None:
    phase(
        "INJECT: retrieval degradation",
        f"Runs {count} real recall() calls against the seeded corpus using "
        "queries semantically distant from every record in it. The vector "
        "search still returns its nearest neighbours, so raw_candidates > 0, "
        "and every one of them falls below the floor. Nothing errors.",
    )
    require_demo(AGENT_MAIN)
    floored = 0
    for query in OFF_TOPIC_QUERIES[:count]:
        hits = recall(AGENT_MAIN, query, session_id=SESSION, conn=conn)
        if not hits:
            floored += 1
        step(f"{'FLOORED' if not hits else 'returned'}  {len(hits)} hit(s)  {query[:50]}")
    step(f"{floored}/{count} retrievals found candidates and returned nothing")


def inject_near_miss(conn: psycopg.Connection, count: int = 9) -> None:
    phase(
        "INJECT: near miss / false negatives",
        f"Runs {count} real recall() calls whose nearest neighbour is the "
        "CORRECT record, but whose score lands just under the floor. These are "
        "not irrelevant queries -- the memory is right there and the retrieval "
        "policy throws it away. A config problem wearing a data problem's "
        "clothes.",
    )
    require_demo(AGENT_MAIN)

    # Injecting this failure means restoring the miscalibrated floor: a
    # previous heal may have already tuned this agent, which would make the
    # injection a no-op. DEFAULT_MIN_SIMILARITY itself is never modified.
    if get_floor(AGENT_MAIN, conn) != DEFAULT_MIN_SIMILARITY:
        with conn.cursor() as cur:
            cur.execute(
                "DELETE FROM agent_config WHERE agent_id = %s AND agent_id LIKE %s",
                (AGENT_MAIN, DEMO_LIKE),
            )
        step(f"re-armed: removed tuned agent_config row, back to {DEFAULT_MIN_SIMILARITY}")

    floor = get_floor(AGENT_MAIN, conn)
    step(f"floor in force for {AGENT_MAIN}: {floor}")
    band_lo = floor - 0.15
    in_band = 0
    for query in NEAR_MISS_QUERIES[:count]:
        stats: dict[str, Any] = {}
        hits = recall(AGENT_MAIN, query, session_id=SESSION, stats=stats, conn=conn)
        score = float(stats["top_similarity"])
        near = (not hits) and band_lo <= score < floor
        in_band += 1 if near else 0
        label = "NEAR-MISS" if near else ("cleared" if hits else "clear miss")
        step(f"{score:.4f}  {label:<10}  {query[:46]}")
    step(f"{in_band}/{count} landed in the near-miss band [{band_lo:.2f}, {floor:.2f})")


def inject_drift(conn: psycopg.Connection) -> None:
    phase(
        "INJECT: vector drift",
        "Writes one record with a NULL embedding and one whose vector is the "
        "right dimension but not unit-normalised. Also attempts a "
        "wrong-dimension vector, which the schema should refuse.",
    )
    require_demo(AGENT_DRIFT)
    now = datetime.now(timezone.utc)

    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO memory_records
                (agent_id, session_id, kind, content, embedding, metadata, effective_as_of)
            VALUES (%s, %s, 'fact', %s, NULL, %s::JSONB, %s)
            """,
            (
                AGENT_DRIFT, SESSION,
                "Record written while the embedding service was timing out.",
                '{"demo": "drift-injection", "case": "null_embedding"}', now,
            ),
        )
    step("wrote 1 record with a NULL embedding")

    # Right dimension, wrong magnitude: a real embedding scaled off the unit ball.
    vector = [v * 3.7 for v in embed("A vector written by a mis-configured client.")]
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO memory_records
                (agent_id, session_id, kind, content, embedding, metadata, effective_as_of)
            VALUES (%s, %s, 'fact', %s, %s::VECTOR, %s::JSONB, %s)
            """,
            (
                AGENT_DRIFT, SESSION,
                "Record written by a client that skipped normalisation.",
                _to_vector(vector),
                '{"demo": "drift-injection", "case": "bad_norm"}', now,
            ),
        )
    step(f"wrote 1 record with norm ~3.7 (expected 1.0 +/- 0.05)")

    # The fourth drift case cannot be injected -- and that is the correct result.
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO memory_records
                    (agent_id, session_id, kind, content, embedding, effective_as_of)
                VALUES (%s, %s, 'fact', 'wrong dimension probe', %s::VECTOR, %s)
                """,
                (AGENT_DRIFT, SESSION, _to_vector([0.1] * 512), now),
            )
        step("WARNING: a 512-dim vector was accepted -- the column is not enforcing width")
    except psycopg.errors.DataException as exc:
        conn.rollback()
        step(f"wrong-dimension insert refused by the schema: {str(exc).splitlines()[0]}")
        step("-> vector_drift's wrong_dim counter stays 0 by construction, not by luck")


def heal_near_miss(conn: psycopg.Connection) -> None:
    """Fix the *policy*, not the data -- this failure class has a config fix.

    Reads the suggestion the near_miss check computed, writes it to
    agent_config for the demo agent, and re-runs the same queries so the
    recovery is demonstrated rather than asserted.
    """
    from checks import check_near_miss  # local import: avoids a cycle at module load

    result = check_near_miss(conn)
    detail = result["detail"]
    suggested = detail.get("suggested_floor")
    current = get_floor(AGENT_MAIN, conn)

    step(f"near_miss check says: {result['severity']}, "
         f"{detail['near_miss']} of {detail['floored_out_total']} floored-out were near misses")
    step(f"suggestion basis: {detail.get('suggestion_basis')}")

    with conn.cursor() as cur:
        cur.execute(
            """
            DELETE FROM memory_retrievals
            WHERE agent_id LIKE %s
              AND results_returned = 0
              AND coalesce(raw_candidates, 0) > 0
              AND top_similarity >= coalesce(applied_floor, %s) - %s
              AND top_similarity < coalesce(applied_floor, %s)
            """,
            (DEMO_LIKE, DEFAULT_MIN_SIMILARITY, 0.15, DEFAULT_MIN_SIMILARITY),
        )
        step(f"removed {cur.rowcount} near-miss demo retrievals")

    if suggested is None:
        step("no suggested floor available -- leaving agent_config unchanged")
        return

    set_floor(AGENT_MAIN, suggested, conn=conn)
    step(f"agent_config: {AGENT_MAIN} floor {current} -> {suggested} (per-agent only; "
         f"DEFAULT_MIN_SIMILARITY stays {DEFAULT_MIN_SIMILARITY})")

    cleared = 0
    for query in NEAR_MISS_QUERIES:
        hits = recall(AGENT_MAIN, query, session_id=SESSION, conn=conn)
        cleared += 1 if hits else 0
        top = f"{hits[0]['similarity']:.4f}" if hits else "floored"
        step(f"  re-run {top:>8}  {len(hits)} hit(s)  {query[:44]}")
    step(f"{cleared}/{len(NEAR_MISS_QUERIES)} now return results at the new floor")


def do_heal(conn: psycopg.Connection, which: str = "all", healthy_recalls: int = 6) -> None:
    targets = (
        ("stale", "eviction", "degradation", "near_miss", "drift")
        if which == "all"
        else (which,)
    )
    phase(
        f"HEAL — reversing: {', '.join(targets)}",
        "Undoes the injected condition so the dashboard recovers on its next "
        "refresh. Only demo- rows are modified.",
    )

    before = protected_counts(conn)

    if "stale" in targets:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE memory_records SET effective_as_of = now()
                WHERE agent_id LIKE %s
                  AND extract(epoch FROM (now() - effective_as_of)) > 3600
                """,
                (DEMO_LIKE,),
            )
            step(f"staleness: refreshed effective_as_of on {cur.rowcount} demo rows")

    if "eviction" in targets:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE memory_records SET expires_at = NULL "
                "WHERE agent_id LIKE %s AND expires_at IS NOT NULL",
                (DEMO_LIKE,),
            )
            step(f"eviction: cleared expires_at on {cur.rowcount} demo rows")

    if "drift" in targets:
        with conn.cursor() as cur:
            cur.execute(
                """
                DELETE FROM memory_records
                WHERE agent_id LIKE %s
                  AND (embedding IS NULL OR abs(vector_norm(embedding) - 1.0) > 0.05)
                """,
                (DEMO_LIKE,),
            )
            step(f"drift: removed {cur.rowcount} demo rows with bad vectors")

    if "near_miss" in targets:
        heal_near_miss(conn)

    if "degradation" in targets:
        with conn.cursor() as cur:
            cur.execute(
                """
                DELETE FROM memory_retrievals
                WHERE agent_id LIKE %s
                  AND results_returned = 0
                  AND coalesce(raw_candidates, 0) > 0
                """,
                (DEMO_LIKE,),
            )
            step(f"degradation: removed {cur.rowcount} floored-out demo retrievals")
        for query in ON_TOPIC_QUERIES[:healthy_recalls]:
            hits = recall(AGENT_MAIN, query, session_id=SESSION, conn=conn)
            step(f"  healthy recall  {len(hits)} hit(s)  {query[:48]}")

    assert_untouched(before, protected_counts(conn))
    step("safety check passed: no non-demo rows were modified")


def do_reset(conn: psycopg.Connection, assume_yes: bool = False) -> None:
    counts = demo_counts(conn)
    total = sum(counts.values())
    phase(
        "RESET — remove every demo row",
        f"Deletes {total} rows where agent_id LIKE '{DEMO_LIKE}' across "
        f"{', '.join(TABLES)}. Non-demo rows, including health events with a "
        "NULL agent_id, are untouched.",
    )
    for table, n in counts.items():
        step(f"{table}: {n} demo rows")

    if not total:
        step("nothing to delete")
        return

    if not assume_yes and not PAUSE:
        try:
            answer = input("  type 'delete' to confirm: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\n  aborted.")
            return
        if answer != "delete":
            step("aborted -- nothing deleted")
            return

    before = protected_counts(conn)
    with conn.cursor() as cur:
        for table in TABLES:
            cur.execute(f"DELETE FROM {table} WHERE agent_id LIKE %s", (DEMO_LIKE,))
            step(f"deleted {cur.rowcount} rows from {table}")
    assert_untouched(before, protected_counts(conn))
    step("safety check passed: no non-demo rows were deleted")


STORY_QUESTION = "which database are we running in production?"


def _ask(agent, question: str, conn: psycopg.Connection):
    """One agent turn, printed with the retrieval telemetry that produced it."""
    turn = agent.answer(question, remember=False, conn=conn)
    step(f"Q: {question}")
    step(
        f"   retrieval {str(turn.retrieval_id)[:8]}  "
        f"raw={turn.raw_candidates} used={turn.memories_used}  "
        f"top_sim={turn.top_similarity if turn.top_similarity is None else round(turn.top_similarity, 4)}  "
        f"floor={turn.applied_floor}  {turn.latency_ms}ms"
    )
    grounding = "GROUNDED" if turn.grounded else "UNGROUNDED — answered with no memory"
    step(f"   {grounding}")
    print()
    for line in textwrap.wrap(turn.response, 68):
        print(f"      {line}")
    print()
    return turn


def do_story(conn: psycopg.Connection) -> None:
    """The full arc: healthy answer -> warning -> broken answer -> recovery.

    The injected failure is targeted eviction of the exact records that answer
    the question.  Off-topic query injection cannot break a *specific* question
    -- it only adds unrelated failing retrievals -- so to show the same question
    degrading, the memory it depends on has to actually become unavailable.
    Eviction does that for real and reverses cleanly.
    """
    from agent import MemoryAgent

    agent = MemoryAgent(AGENT_MAIN, SESSION)

    phase(
        "STORY 1/5 — SEED",
        "Write the corpus and establish a healthy retrieval baseline.",
    )
    do_seed(conn, recalls=4)

    phase(
        "STORY 2/5 — HEALTHY: the agent answers from memory",
        f"The agent is asked {STORY_QUESTION!r}. It retrieves the relevant "
        "records and answers from them. Note the retrieval id — every turn "
        "records which retrieval fed it.",
    )
    healthy = _ask(agent, STORY_QUESTION, conn)
    if not healthy.grounded:
        step("WARNING: baseline turn was not grounded — the story needs a healthy start")

    fed_ids = [m["id"] for m in healthy.memories]
    step(f"this answer was built from {len(fed_ids)} memory record(s)")

    phase(
        "STORY 3/5 — WARNING: health degrades BEFORE the answer does",
        "This agent's whole memory is given an expires_at inside the eviction "
        "window -- the realistic shape of the failure, a corpus aging out, not "
        "two rows vanishing. The records are still live and still retrievable, "
        "so the answer is unchanged -- but eviction_pressure fires NOW. That is "
        "the thesis: the dashboard warns while the answers are still correct.",
    )
    with conn.cursor() as cur:
        # Expire the agent's entire corpus, not just the rows feeding this one
        # question. Eviction pressure is a *share* of live rows, and one
        # question's worth is never a meaningful share -- scoping it that
        # tightly left the check green and made the demo argue against itself.
        cur.execute(
            """
            UPDATE memory_records SET expires_at = now() + INTERVAL '45 minutes'
            WHERE agent_id = %s AND agent_id LIKE %s
            """,
            (AGENT_MAIN, DEMO_LIKE),
        )
        step(f"set expires_at on {cur.rowcount} record(s) (whole corpus), 45 minutes out")
    evic = checks.check_eviction_pressure(conn)
    step(
        f"eviction_pressure -> {evic['severity'].upper()} "
        f"({evic['detail']['expiring_within_horizon']} of "
        f"{evic['detail']['live_rows']} live rows, {evic['detail']['expiring_pct']}%)"
    )
    still_ok = _ask(agent, STORY_QUESTION, conn)
    step(
        "the answer is still correct — the health signal moved first"
        if still_ok.grounded
        else "unexpected: the agent already lost grounding"
    )

    phase(
        "STORY 4/5 — FAILURE: the memory expires, the agent goes blind",
        "The same records expire. recall() filters expired rows, so the same "
        "question now retrieves NOTHING AT ALL -- not a weak match, zero "
        "candidates -- and the agent answers without context. Nothing errors. "
        "Nothing retries. The agent simply stops knowing.",
    )
    with conn.cursor() as cur:
        cur.execute(
            """
            UPDATE memory_records SET expires_at = now() - INTERVAL '1 minute'
            WHERE agent_id = %s AND agent_id LIKE %s
            """,
            (AGENT_MAIN, DEMO_LIKE),
        )
        step(f"expired {cur.rowcount} record(s) -- the corpus is now gone from retrieval")
    broken = _ask(agent, STORY_QUESTION, conn)

    # Report which check owns this failure. The interesting result is that
    # empty_resolve stays OK: it counts retrievals that found candidates and
    # cleared none -- a *relevance* failure. This is an *availability* failure,
    # and the checks are supposed to tell those apart rather than both firing.
    evic2 = checks.check_eviction_pressure(conn)
    empty = checks.check_empty_resolve(conn)
    step(
        f"eviction_pressure -> {evic2['severity'].upper()} "
        f"({evic2['detail']['expiring_within_horizon']} of "
        f"{evic2['detail']['live_rows']} live rows) -- it went CRITICAL one "
        f"beat ago and is quiet now for the worst reason: the rows it was "
        f"warning about are already gone, so there is no pressure left"
    )
    step(
        f"empty_resolve     -> {empty['severity'].upper()} "
        f"({empty['detail']['floored_out']} floored out of "
        f"{empty['detail']['retrievals']}) -- correctly quiet: nothing was "
        f"rejected, there was nothing to reject"
    )
    step(
        f"agent_turns       -> memories_used=0, raw_candidates="
        f"{broken.raw_candidates} -- the agent answered blind"
    )
    if broken.retrieval_id:
        step(f"the bad answer traces to retrieval {broken.retrieval_id}")

    phase(
        "STORY 5/5 — HEAL: restore the memory, the agent recovers",
        "expires_at is cleared. The same question, the same agent, the same "
        "model -- the only thing that changed is whether the memory was there.",
    )
    before = protected_counts(conn)
    with conn.cursor() as cur:
        cur.execute(
            "UPDATE memory_records SET expires_at = NULL "
            "WHERE agent_id = %s AND agent_id LIKE %s",
            (AGENT_MAIN, DEMO_LIKE),
        )
        step(f"restored {cur.rowcount} record(s)")
    healed = _ask(agent, STORY_QUESTION, conn)
    assert_untouched(before, protected_counts(conn))
    step("safety check passed: no non-demo rows were modified")

    print()
    print("  ── the arc ─────────────────────────────────────────────────────")
    for label, turn in (("healthy", healthy), ("warning", still_ok),
                        ("expired", broken), ("healed", healed)):
        mark = "grounded" if turn.grounded else "BLIND"
        print(f"    {label:<9} memories={turn.memories_used}  {mark}")


def do_timeline(
    conn: psycopg.Connection,
    hours: int = 6,
    buckets: int = 6,
    per_bucket: int = 4,
) -> None:
    """seed -> healthy -> degradation -> recovery, spread across a real window.

    The retrievals are real: real embeddings, real similarity scores, real
    floor decisions.  What is staged is their retrieved_at -- demo rows are
    redistributed across the window so the 24h charts show an arc instead of
    one dense bucket.  Only demo- rows are ever time-shifted.
    """
    phase(
        "TIMELINE — a story arc across the last "
        f"{hours}h ({buckets} buckets x {per_bucket} retrievals)",
        "Runs real recalls in four acts (healthy, degrading, degraded, "
        "recovering), then redistributes their timestamps across the window so "
        "the dashboard's 24h charts show the shape rather than a single point. "
        "Timestamps are staged; every similarity score is real.",
    )

    do_seed(conn, recalls=4)

    # act shape: fraction of each bucket's queries that are off-topic
    shape = [0.0, 0.25, 0.75, 1.0, 0.5, 0.0][:buckets]
    while len(shape) < buckets:
        shape.append(0.0)

    now = datetime.now(timezone.utc)
    window = timedelta(hours=hours)
    bucket_span = window / buckets
    start = now - window

    total_ids: list[tuple[Any, datetime]] = []
    for b in range(buckets):
        off_count = round(shape[b] * per_bucket)
        bucket_start = start + bucket_span * b
        step(
            f"bucket {b + 1}/{buckets}  {bucket_start:%H:%M}  "
            f"{off_count} off-topic / {per_bucket - off_count} on-topic"
        )
        for i in range(per_bucket):
            off = i < off_count
            pool = OFF_TOPIC_QUERIES if off else ON_TOPIC_QUERIES
            query = pool[(b * per_bucket + i) % len(pool)]
            # stats carries the row id back: retrieved_at cannot identify it,
            # since every row in this transaction shares the same now().
            stats: dict[str, Any] = {}
            recall(AGENT_MAIN, query, session_id=SESSION, stats=stats, conn=conn)
            offset = bucket_span * (i + 0.5) / per_bucket
            total_ids.append((stats["retrieval_id"], bucket_start + offset))

    before = protected_counts(conn)
    with conn.cursor() as cur:
        for retrieval_id, stamp in total_ids:
            cur.execute(
                "UPDATE memory_retrievals SET retrieved_at = %s "
                "WHERE id = %s AND agent_id LIKE %s",
                (stamp, retrieval_id, DEMO_LIKE),
            )
    assert_untouched(before, protected_counts(conn))
    step(f"redistributed {len(total_ids)} demo retrievals across the last {hours}h")
    step("safety check passed: no non-demo rows were modified")


# ---------------------------------------------------------------------------
def summarise(conn: psycopg.Connection) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT count(*) AS retrievals,
                   count(*) FILTER (
                       WHERE results_returned = 0 AND coalesce(raw_candidates, 0) > 0
                   ) AS floored
            FROM memory_retrievals
            WHERE extract(epoch FROM (now() - retrieved_at)) <= 3600
            """
        )
        window = cur.fetchone()
    counts = demo_counts(conn)
    print()
    print("  demo rows:", ", ".join(f"{t.split('_', 1)[1]}={n}" for t, n in counts.items()))
    rate = (
        100.0 * window["floored"] / window["retrievals"] if window["retrievals"] else 0.0
    )
    print(
        f"  last 60m: {window['retrievals']} retrievals, "
        f"{window['floored']} floored out ({rate:.1f}%)"
    )
    print("  dashboard: http://127.0.0.1:8000")


def main(argv: list[str] | None = None) -> int:
    global PAUSE
    parser = argparse.ArgumentParser(
        description="Labeled, reversible failure injection for the Memory Health demo."
    )
    parser.add_argument("--pause", action="store_true", help="stop before each phase")
    sub = parser.add_subparsers(dest="mode", required=True)

    p_seed = sub.add_parser("seed", help="write the demo corpus + a healthy baseline")
    p_seed.add_argument("--recalls", type=int, default=8)

    p_inject = sub.add_parser("inject", help="introduce one failure class for real")
    p_inject.add_argument(
        "failure", choices=("stale", "eviction", "degradation", "near_miss", "drift")
    )
    p_inject.add_argument("--count", type=int, default=None)

    p_heal = sub.add_parser("heal", help="reverse an injected condition")
    p_heal.add_argument(
        "failure", nargs="?", default="all",
        choices=("all", "stale", "eviction", "degradation", "near_miss", "drift"),
    )

    p_reset = sub.add_parser("reset", help="delete every demo- row")
    p_reset.add_argument("--yes", action="store_true", help="skip the confirmation")

    sub.add_parser("story", help="the full arc: healthy -> warn -> blind -> recovered")

    p_time = sub.add_parser("timeline", help="seed -> healthy -> degrade -> heal")
    p_time.add_argument("--hours", type=int, default=6)
    p_time.add_argument("--buckets", type=int, default=6)
    p_time.add_argument("--per-bucket", type=int, default=4)

    args = parser.parse_args(argv)
    PAUSE = args.pause
    random.seed(20260808)

    with connect() as conn:
        if args.mode == "seed":
            do_seed(conn, recalls=args.recalls)
        elif args.mode == "inject":
            if args.failure == "stale":
                inject_stale(conn, count=args.count or 6)
            elif args.failure == "eviction":
                inject_eviction(conn, count=args.count or 8)
            elif args.failure == "degradation":
                inject_degradation(conn, count=args.count or 10)
            elif args.failure == "near_miss":
                inject_near_miss(conn, count=args.count or 9)
            else:
                inject_drift(conn)
        elif args.mode == "heal":
            do_heal(conn, which=args.failure)
        elif args.mode == "reset":
            do_reset(conn, assume_yes=args.yes)
        elif args.mode == "story":
            do_story(conn)
        elif args.mode == "timeline":
            do_timeline(
                conn, hours=args.hours, buckets=args.buckets, per_bucket=args.per_bucket
            )
        summarise(conn)
    return 0


if __name__ == "__main__":
    sys.exit(main())
